Remove pytest from pre-commit hook
This hook failed when trying to commit changes using magit in emacs.

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -24,13 +24,13 @@ echo
     exit 1
 fi
 
-if ! pytest
-then
-    echo "pytest failed...commit anyway [y/n]"
-    read answer
-    case answer in
-        y) exit 0
-            ;;
-        *) exit 1 ;;
-    esac
-fi
+# if ! pytest
+# then
+#     echo "pytest failed...commit anyway [y/n]"
+#     read answer
+#     case answer in
+#         y) exit 0
+#             ;;
+#         *) exit 1 ;;
+#     esac
+# fi
